### ISSUE TITLE
AS A user I WANT TO get current readings from device

### ISSUE THREAD

**Issue by micdra01** [easv-devops/Climate#4]
Backend:
- [x] Get latest readings from ESP32-E (temp. humidity, particles)
- [x] Save to DB (temp, humi, part)
- [ ] Show to connected sockets  --(Venter Med denne til device delen er færdig i frontend og beckend.)

Database: 
- [x] Tabeller til readings (temp, humidity, particles2.5, particle10)

Esp32:
- [x] Read temp
- [x] Read humi
- [x] Read Parti

Andet:
- [x] MQTT broker (topics)

**Comment by JennyTromTheBlock** [comment]
Mock device færdig, pull request for at tilføje den til main, mangler stadigt humi og temp sensor

**Comment by JennyTromTheBlock** [comment]
pull request til master
